# Generated by Django 2.2.2 on 2020-07-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='home_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sale_type',
        ),
    ]
