# Generated by Django 2.2.2 on 2020-07-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200723_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('CONDO', 'Condo'), ('TOWNHOUSE', 'Townhouse')], default=('HOUSE', 'House'), max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('FOR_SALE', 'For Sale'), ('FOR_RENT', 'For Rent')], default=('FOR_SALE', 'For Sale'), max_length=50),
        ),
    ]
