# Generated by Django 2.2.2 on 2020-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200723_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse')], default=('House', 'House'), max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default=('For Sale', 'For Sale'), max_length=50),
        ),
    ]
