# Generated by Django 2.2.2 on 2020-07-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200725_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('CONDO', 'Condo'), ('TOWNHOUSE', 'Townhouse')], default=('HOUSE', 'House'), max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('FOR SALE', 'For Sale'), ('FOR RENT', 'For Rent')], default=('FOR SALE', 'For Sale'), max_length=50),
        ),
    ]
